// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewCreateContactRequest(
	name AccountObjectIdentifier,
	Email string,
) *CreateContactRequest {
	s := CreateContactRequest{}
	s.name = name
	s.Email = Email
	return &s
}

func (s *CreateContactRequest) WithOrReplace(OrReplace bool) *CreateContactRequest {
	s.OrReplace = &OrReplace
	return s
}

func (s *CreateContactRequest) WithIfNotExists(IfNotExists bool) *CreateContactRequest {
	s.IfNotExists = &IfNotExists
	return s
}

func (s *CreateContactRequest) WithComment(Comment string) *CreateContactRequest {
	s.Comment = &Comment
	return s
}

func NewAlterContactRequest(
	name AccountObjectIdentifier,
) *AlterContactRequest {
	s := AlterContactRequest{}
	s.name = name
	return &s
}

func (s *AlterContactRequest) WithIfExists(IfExists bool) *AlterContactRequest {
	s.IfExists = &IfExists
	return s
}

func (s *AlterContactRequest) WithSet(Set ContactSetRequest) *AlterContactRequest {
	s.Set = &Set
	return s
}

func (s *AlterContactRequest) WithUnset(Unset ContactUnsetRequest) *AlterContactRequest {
	s.Unset = &Unset
	return s
}

func (s *AlterContactRequest) WithRenameTo(RenameTo AccountObjectIdentifier) *AlterContactRequest {
	s.RenameTo = &RenameTo
	return s
}

func NewContactSetRequest() *ContactSetRequest {
	return &ContactSetRequest{}
}

func (s *ContactSetRequest) WithEmail(Email string) *ContactSetRequest {
	s.Email = &Email
	return s
}

func (s *ContactSetRequest) WithComment(Comment string) *ContactSetRequest {
	s.Comment = &Comment
	return s
}

func NewContactUnsetRequest() *ContactUnsetRequest {
	return &ContactUnsetRequest{}
}

func (s *ContactUnsetRequest) WithComment(Comment bool) *ContactUnsetRequest {
	s.Comment = &Comment
	return s
}

func NewDropContactRequest(
	name AccountObjectIdentifier,
) *DropContactRequest {
	s := DropContactRequest{}
	s.name = name
	return &s
}

func (s *DropContactRequest) WithIfExists(IfExists bool) *DropContactRequest {
	s.IfExists = &IfExists
	return s
}

func NewShowContactRequest() *ShowContactRequest {
	return &ShowContactRequest{}
}

func (s *ShowContactRequest) WithLike(Like Like) *ShowContactRequest {
	s.Like = &Like
	return s
}

func NewDescribeContactRequest(
	name AccountObjectIdentifier,
) *DescribeContactRequest {
	s := DescribeContactRequest{}
	s.name = name
	return &s
}
