// Code generated by config model builder generator; DO NOT EDIT.

package model

import (
	"encoding/json"

	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/resources"
)

type ContactModel struct {
	Name               tfconfig.Variable `json:"name,omitempty"`
	Email              tfconfig.Variable `json:"email,omitempty"`
	Comment            tfconfig.Variable `json:"comment,omitempty"`
	FullyQualifiedName tfconfig.Variable `json:"fully_qualified_name,omitempty"`

	DynamicBlock *config.DynamicBlock `json:"dynamic,omitempty"`

	*config.ResourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func Contact(
	resourceName string,
	name string,
	email string,
) *ContactModel {
	c := &ContactModel{ResourceModelMeta: config.Meta(resourceName, resources.Contact)}
	c.WithName(name)
	c.WithEmail(email)
	return c
}

func ContactWithDefaultMeta(
	name string,
	email string,
) *ContactModel {
	c := &ContactModel{ResourceModelMeta: config.DefaultMeta(resources.Contact)}
	c.WithName(name)
	c.WithEmail(email)
	return c
}

///////////////////////////////////////////////////////////////////////
// set proper json marshalling, handle depends on and dynamic blocks //
///////////////////////////////////////////////////////////////////////

func (c *ContactModel) MarshalJSON() ([]byte, error) {
	type Alias ContactModel
	return json.Marshal(&struct {
		*Alias
		DependsOn []string `json:"depends_on,omitempty"`
	}{
		Alias:     (*Alias)(c),
		DependsOn: c.DependsOn(),
	})
}

func (c *ContactModel) WithDependsOn(values ...string) *ContactModel {
	c.SetDependsOn(values...)
	return c
}

func (c *ContactModel) WithDynamicBlock(dynamicBlock *config.DynamicBlock) *ContactModel {
	c.DynamicBlock = dynamicBlock
	return c
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

func (c *ContactModel) WithName(name string) *ContactModel {
	c.Name = tfconfig.StringVariable(name)
	return c
}

func (c *ContactModel) WithEmail(email string) *ContactModel {
	c.Email = tfconfig.StringVariable(email)
	return c
}

func (c *ContactModel) WithComment(comment string) *ContactModel {
	c.Comment = tfconfig.StringVariable(comment)
	return c
}

func (c *ContactModel) WithFullyQualifiedName(fullyQualifiedName string) *ContactModel {
	c.FullyQualifiedName = tfconfig.StringVariable(fullyQualifiedName)
	return c
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (c *ContactModel) WithNameValue(value tfconfig.Variable) *ContactModel {
	c.Name = value
	return c
}

func (c *ContactModel) WithEmailValue(value tfconfig.Variable) *ContactModel {
	c.Email = value
	return c
}

func (c *ContactModel) WithCommentValue(value tfconfig.Variable) *ContactModel {
	c.Comment = value
	return c
}

func (c *ContactModel) WithFullyQualifiedNameValue(value tfconfig.Variable) *ContactModel {
	c.FullyQualifiedName = value
	return c
}
